# Opening the results file

In [ ]:
import pandas as pd

data = pd.read_csv("/Users/alessiofantasia/prediction-wc/data/results.csv", parse_dates=[0], index_col=[0])

print(data)

# Reading results csv information

In [44]:
data.head(10)
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 49477 entries, 1872-11-30 to 2026-06-27
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   home_team   49477 non-null  object
 1   away_team   49477 non-null  object
 2   home_score  49433 non-null  float64
 3   away_score  49433 non-null  float64
 4   tournament  49477 non-null  object
 5   city        49477 non-null  object
 6   country     49477 non-null  object
 7   neutral     49477 non-null  bool
dtypes: bool(1), float64(2), object(5)
memory usage: 3.1+ MB

         home_score    away_score
count  49433.000000  49433.000000
mean       1.757490      1.181822
std        1.774299      1.401856
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

# Plotting Data

In [ ]:
data["home_score"].plot()
data["away_score"].plot()

# Combining Excel Files

In [38]:
from glob import glob

path = "/Users/alessiofantasia/prediction-wc/data"
files = sorted(glob(path + "/*.csv"))

print(files)

['/Users/alessiofantasia/prediction-wc/data/former_names.csv', '/Users/alessiofantasia/prediction-wc/data/goalscorers.csv', '/Users/alessiofantasia/prediction-wc/data/results.csv', '/Users/alessiofantasia/prediction-wc/data/shootouts.csv']

In [ ]:
data_combined = pd.concat([pd.read_csv(f, index_col=[0], parse_dates=[0]) for f in files])
print(data_combined)

In [46]:
data_combined = pd.concat([pd.read_csv(f, index_col=[0], parse_dates=[0]) for f in files])

data_combined.head(10)
data_combined.info()
data_combined.describe()

/var/folders/bp/2fqx7b0j5l3d3v0x2xnp3zgw0000gn/T/ipykernel_75588/3332927194.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data_combined = pd.concat([pd.read_csv(f, index_col=[0], parse_dates=[0]) for f in files])

<class 'pandas.core.frame.DataFrame'>
Index: 97881 entries, Benin to 2026-06-06 00:00:00
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   former         36 non-null     object
 1   start_date     36 non-null     object
 2   end_date       36 non-null     object
 3   home_team      97845 non-null  object
 4   away_team      97845 non-null  object
 5   team           47690 non-null  object
 6   scorer         47642 non-null  object
 7   minute         47434 non-null  float64
 8   own_goal       47690 non-null  object
 9   penalty        47690 non-null  object
 10  home_score     49433 non-null  float64
 11  away_score     49433 non-null  float64
 12  tournament     49477 non-null  object
 13  city           49477 non-null  object
 14  country        49477 non-null  object
 15  neutral        49477 non-null  object
 16  winner         678 non-null    object
 17  first_shooter  256 non-null    object
dtypes: float64(3), object(15)
memory usage: 14.2+ MB

             minute    home_score    away_score
count  47434.000000  49433.000000  49433.000000
mean      50.056289      1.757490      1.181822
std       26.365638      1.774299      1.401856
min        1.000000      0.000000      0.000000
25%       28.000000      1.000000      0.000000
50%       51.000000      1.000000      1.000000
75%       73.000000      2.000000      2.000000
max      122.000000     31.000000     21.000000